### PR TITLE
My first Pull Request

### PR DESCRIPTION
**Pull request by jorgegoco**

### CODE REVIEW

**Review by topeogunleye — CHANGES_REQUESTED** [review]
> # Changes Required
> ### Hi @Mugiira-Kim,
> Nice job, you are almost there.
> 
> 
> 
> ## (Highlights) Good Points: 
> * Github flow is used :heavy_check_mark:.
> * No linter errors. :heavy_check_mark:
> * PR has a good title and summary :heavy_check_mark:
> 
> ## (Changes Required) Aspects to improve: 
> * [ ]  Please check my inline comments.
>- [ ] I suggest you kindly add a README file to your repo as this will give users detailed information about your project.
>- [ ] From now on, kindly make use of imperative mood in the subject line for your commit messages.
:x: Wrong
Screenshot from 2022-04-20 08-55-14
> ### Good Commit Messages:
>- [x]  Add fix for dark mode toggle state
>- [x] Update README file.
>- [x] Add styles to h1.
>
>- [ ] Please kindly add a more descriptive PR title and description.
> See an example below:
>Screenshot from 2022-04-19 17-33-33
> ## [Optional] suggestions:
> * Kindly check my inline comments.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> **Cheers and Happy coding! :clap::clap::clap:**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> Please, remember to tag @topeogunleye in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by jorgegoco** [comment]
Thank you @topeogunleye for your review, you asked me for a README file but it's already there and I used the template given to us.

**Review by chrystalme — APPROVED** [review]
# Hi @jorgegoco 🚀 

## Your project meets the requirements ✅ 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it


Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Also, you can reach me on [Twitter](https://twitter.com/afam_ifeanyi) or [Slack](https://microverse-community.slack.com/team/U019ZC99KFA)

**Comment by jorgegoco** [comment]
Thank you for the review @chrystalme

**Comment by topeogunleye** [comment]
> Thank you @topeogunleye for your review, you asked me for a README file but it's already there and I used the template given to us.

I missed it. sorry about that. I'm Glad your project was approved.

**Comment by chrystalme** [comment]
> Thank you for the review @chrystalme 

You are welcome

**Pull request merged**
